### PR TITLE
CMake Support

### PR DESCRIPTION
**Pull request by jchristopherson**
Hi @vmagnin.  Please consider adding the CMake support provided by this pull request.  A github workflow for the CMake build is also included.  Thanks!

### CODE REVIEW

**Comment by vmagnin** [comment]
Thanks @jchristopherson for this great and useful contribution!

I will document the CMake support in the main README.md when I have some time. And I did not know CMake could manage git dependencies.

And the github workflow will be useful as it includes two OS and two compilers.

**Comment by gha3mi** [comment]
@jchristopherson, as a suggestion, you might consider creating simple instructions for fpm users to make the fpm packages available for cmake as well. One of the reasons I switched to fpm was because of the dependencies, which I wasn't initially aware of. I believe it would be helpful if instructions were available for this purpose.

**Comment by jchristopherson** [comment]
Hi @gha3mi.  I can add instructions on how to accomplish this in CMake, but what is the best location to add these instructions?  To me, this seems to be something outside of this repository.  Perhaps its own repository?  My CMake is relatively similar between different applications.  Perhaps I create a repository dedicated to CMake stuff?  I'm definitely open to suggestions here.

One thing though, to be quite frank, FPM does offer the cleaner solution many times.  FPM is often times just simpler to use.  Even so, I still use CMake quite a bit, but mainly for legacy reasons.

**Comment by gha3mi** [comment]
Yes, creating a repository for this purpose is a good idea. Including simple examples demonstrating various situations would be valuable. Providing complete scenarios with tests, examples, and dependencies would be beneficial. If it can be generalized, users might be able to use it as a 'git submodule' in their repositories. (This is just an idea, and I'm not certain if it's feasible!). Whats your opinion @vmagnin?

Personally, I used Make before fpm. I put in a lot of effort to create a Make environment aiming to avoid the need to recreate a similar environment for every project. However, after releasing fpm, I switched because it's straightforward and easier to work with.

**Comment by vmagnin** [comment]
> Yes, creating a repository for this purpose is a good idea. Including simple examples demonstrating various situations would be valuable. Providing complete scenarios with tests, examples, and dependencies would be beneficial. If it can be generalized, users might be able to use it as a 'git submodule' in their repositories. (This is just an idea, and I'm not certain if it's feasible!). Whats your opinion @vmagnin?

I don't know if it is feasible. But a repository demonstrating useful CMake things could be interesting. Maybe it already exists? (for other languages).
Personally, I was interested especially by the dependencies management, which I did not know. I am not a CMake expert, I am just maintaining it in the gtk-fortran project.

**Comment by vmagnin** [comment]
By the way, I tried to install forcolormap in the system but failed:
```bash
$ sudo make install
[ 46%] Built target forimage
[100%] Built target forcolormap
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /usr/local/lib/libforimage.a
-- Up-to-date: /usr/local/include
-- Up-to-date: /usr/local/include/lut.mod
-- Up-to-date: /usr/local/include/pnm.mod
-- Up-to-date: /usr/local/include/forimage_parameters.mod
-- Up-to-date: /usr/local/include/forcolor.mod
-- Up-to-date: /usr/local/include/forimage.mod
CMake Error at _deps/forimage-build/install/cmake_install.cmake:70 (file):
  file INSTALL cannot find "forcolormap/build/_deps/forimage-src/include": No such
  file or directory.
Call Stack (most recent call first):
  _deps/forimage-build/cmake_install.cmake:52 (include)
  dependencies/forimage/cmake_install.cmake:47 (include)
  dependencies/cmake_install.cmake:47 (include)
  cmake_install.cmake:47 (include)

make: *** [Makefile:100 : install] Erreur 1

forcolormap/build (main)$ ls _deps/forimage-src/
CMakeLists.txt  ford.yml  install  lut_files  png_files  README.md  test     workspace.code-workspace
example         fpm.toml  LICENSE  media      pnm_files  src        VERSION
```
The directory `forcolormap/build/_deps/forimage-src/include` does not exist.

**Comment by jchristopherson** [comment]
Hi @vmagnin ,
I'll look at it and report back.

**Comment by jchristopherson** [comment]
@vmagnin, @gha3mi,
I've traced the issue back to the CMake script with the dependency forimage.  I will submit a pull request on both forimage and this library taking care of the issue.

**Comment by jchristopherson** [comment]
As for the repository for CMake related stuff, I'll check into it.  I've seen a few different flavors of this idea around.  I'll do some work towards this idea.

**Pull request merged**
